In [13]:
import numpy as np

mark = np.array([88, 90, 30, 45, 75])

mark = mark + 5

print(mark)



[93 95 35 50 80]


In [14]:
mark=mark-5
mark/2
print(mark)

[88 90 30 45 75]


In [15]:
mark>45

array([ True,  True, False, False,  True])

In [16]:
print(mark[0])
print(mark)

88
[88 90 30 45 75]


In [17]:
print(mark[0])
print(mark[-1])
print(mark[3])

88
75
45


In [19]:
for i in range(4):
    print(mark[i])

88
90
30
45


In [20]:
mark[0:2]
mark[0:2][0:2]

array([88, 90])

In [27]:


mark = np.array([
    [85, 78, 90],
    [92, 85, 98],
    [56, 89, 74]
])

print(mark)


[[85 78 90]
 [92 85 98]
 [56 89 74]]


In [31]:
mark[0][0:2]

array([85, 78])

In [ ]:
b1=np.array([56,78,92])
b2=np.array([68,42,54])

comb=np.concatenate((b1,b2))
comb

array([56, 78, 92, 68, 42, 54])

In [38]:
print(np.split(comb,2))
for arr in np.split(comb,3):
    print(arr)

[array([56, 78, 92]), array([68, 42, 54])]
[56 78]
[92 68]
[42 54]


In [43]:
mark = np.array([
    [85, 78, 90],
    [92, 85, 98],
    [56, 89, 74]
])

print(mark[np.where(mark>= 80)])
print(mark)

[85 90 92 85 98 89]
[[85 78 90]
 [92 85 98]
 [56 89 74]]


In [47]:
np.sort(mark)[::-1]

array([[56, 74, 89],
       [85, 92, 98],
       [78, 85, 90]])